Modify input defaults and descriptions in SHRP workflow
Updated default values and descriptions for workflow inputs in SHRP.yml.

diff --git a/.github/workflows/SHRP.yml b/.github/workflows/SHRP.yml
--- a/.github/workflows/SHRP.yml
+++ b/.github/workflows/SHRP.yml
@@ -1,34 +1,34 @@
-name: SHRP Builder
+Name: SHRP Builder
 on:
   workflow_dispatch:
     inputs:
       MANIFEST_URL:
         description: 'Manifest'
         required: true
-        default: ''
+        default: 'https://github.com/nitheshd30/SHRP_Manifest.git'
         type: choice
         options:
         - https://github.com/nitheshd30/SHRP_Manifest.git
       MANIFEST_BRANCH:
         description: 'Manifest Branch'
         required: true
-        default: ''
+        default: 'v3_11.0'
         type: choice
         options:
         - v3_11.0
       DEVICE_TREE:
-        description: 'Custom Recovery Tree' # Your already made Device Tree for TWRP
+        description: 'Custom Recovery Tree'
         required: true
-        default: ''
+        default: 'https://github.com/nitheshd30/SHRP_Builder.git'
         type: choice
         options:
         - https://github.com/nitheshd30/SHRP_Builder.git
         - https://github.com/end222/android_device_xiaomi_curtana-pbrp.git
         - https://github.com/nitheshd30/OFRP-device_nothing_Spacewar.git
       DEVICE_TREE_BRANCH:
-        description: 'Custom Recovery Tree Branch' # Your Device Tree Branch, make sure it's right.
+        description: 'Custom Recovery Tree Branch'
         required: true
-        default: ''
+        default: 'master'
         type: choice
         options:
         - master
@@ -37,33 +37,178 @@ on:
         - fox_11.0
         - android-10.0
       DEVICE_PATH:
-        description: 'Specify your Device Path' # As is, just like your DEVICE_PATH in your BoardConfig.mk
+        description: 'Specify your Device Path'
         required: true
-        default: ''
+        default: 'device/nothing/Spacewar'
         type: choice
         options:
         - device/nothing/Spacewar
         - device/infinix/X6812
       DEVICE_NAME:
-        description: 'Specify your Device Codename' # As is, just like your PRODUCT_DEVICE in your device tree.
+        description: 'Specify your Device Codename'
         required: true
-        default: ''
+        default: 'Spacewar'
         type: choice
         options:
         - Spacewar
         - X6812
       MAKEFILE_NAME:
-        description: 'Specify your Makefile Name' # Look for twrp_ or omni_codename.mk, just remove the .mk
+        description: 'Specify your Makefile Name'
         required: true
-        default: ''
+        default: 'twrp_X6812'
         type: choice
         options:
         - twrp_X6812
         - omni_Infinix-X6812
         - twrp_Spacewar
       BUILD_TARGET:
-        description: 'Specify your Build Target' # Pick among boot, recovery and vendor_boot
+        description: 'Specify your Build Target'
         required: true
+        default: 'boot'
+        type: choice
+        options:
+        - boot
+        - recovery
+        - vendorboot
+      FILE_TO_CHECK:
+        description: 'Specify which libs to check'
+        required: false
+        default: 'system/bin/qseecomd'
+
+jobs:
+  build:
+    if: github.event.repository.owner.id == github.event.sender.id
+    runs-on: ubuntu-22.04
+    permissions:
+      contents: write
+    steps:
+    - name: Check Out
+      uses: actions/checkout@v3
+
+    - name: Display Inputs
+      run: |
+        echo "Displaying variables/inputs."
+        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
+        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
+        echo "Device Tree: ${{ github.event.inputs.DEVICE_TREE }}"
+        echo "Device Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
+        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
+        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
+        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
+        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}image"
+
+    - name: Cleanup
+      uses: rokibhasansagar/slimhub_actions@main
+
+    - name: Set Swap Space
+      uses: pierotofy/set-swap-space@master
+      with:
+        swap-size-gb: 12
+
+    - name: Prepare the Environment
+      run: |
+        sudo apt update
+        sudo apt -y upgrade
+        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev python3 python-is-python3 libtinfo5
+        
+    - name: Install OpenJDK
+      uses: actions/setup-java@v3
+      with:
+        distribution: 'zulu'
+        java-version: '8'
+
+    - name: Install Git-Repo
+      run: |
+        mkdir -p ~/bin
+        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
+        chmod a+x ~/bin/repo
+        sudo ln -sf ~/bin/repo /usr/bin/repo
+
+    - name: Initialize Repo
+      id: pwd
+      run: |
+        mkdir workspace
+        cd workspace
+        echo "workdir=$(pwd)" >> $GITHUB_OUTPUT
+        git config --global user.name "${{ github.actor }}"
+        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
+        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
+        
+    - name: Repo Sync
+      run: |
+        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
+      working-directory: workspace
+      
+    - name: Clone Device Tree
+      run: |
+        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
+      working-directory: ${{ steps.pwd.outputs.workdir }}
+
+    - name: Check Build Tree
+      uses: haya14busa/action-cond@v1
+      id: buildtree
+      with:
+        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1' }}
+        if_true: twrp
+        if_false: omni
+
+    - name: Sync Dependencies
+      run: |
+        bash ${GITHUB_WORKSPACE}/scripts/convert.sh ${{ github.event.inputs.DEVICE_PATH }}/${{ steps.buildtree.outputs.value }}.dependencies
+        repo sync -j$(nproc --all)
+      working-directory: ${{ steps.pwd.outputs.workdir }}
+      continue-on-error: true
+
+    - name: Building Recovery
+      run: |
+        source build/envsetup.sh
+        export ALLOW_MISSING_DEPENDENCIES=true
+        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng && make clean && make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
+        echo "Done building your ${{ github.event.inputs.BUILD_TARGET }}.img"
+      working-directory: ${{ steps.pwd.outputs.workdir }}
+
+    - name: Set Properties
+      id: props
+      run: |
+        echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
+        
+    - name: Renaming into TWRP
+      run: |
+        cd out/target/product/${{ github.event.inputs.DEVICE_NAME }}
+        mv ${{ github.event.inputs.BUILD_TARGET }}.img ${{ github.event.inputs.MANIFEST_BRANCH }}-SHRP-${{ github.event.inputs.DEVICE_NAME }}-${{ steps.props.outputs.date }}.img
+        echo "Done renaming into ${{ github.event.inputs.MANIFEST_BRANCH }}-SHRP-${{ github.event.inputs.DEVICE_NAME }}-${{ steps.props.outputs.date }}.img"
+      working-directory: ${{ steps.pwd.outputs.workdir }}
+      
+    - name: Upload to Release
+      uses: ncipollo/release-action@v1.12.0
+      with:
+        artifacts: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.MANIFEST_BRANCH }}*.img
+        name: Unofficial-Alpha SHRP for ${{ github.event.inputs.DEVICE_NAME }} - Build ${{ steps.props.outputs.date }} / ${{ github.run_id }}
+        draft: false
+        prerelease: true
+        tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
+        token: ${{ secrets.GITHUB_TOKEN }}
+        body: |
+          Device: ${{ github.event.inputs.DEVICE_NAME }}
+          Manifest: ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
+          Status: Alpha - Test it Yourself.
+
+    - name: Clone LDChecker
+      run: |
+        git clone https://github.com/cd-Spidey/Random ./ldcheck
+        cd ldcheck/extract-tools
+        # Attempt to move only if files exist to prevent failure
+        [ -f qseecomd ] && mv -n qseecomd ${GITHUB_WORKSPACE}/workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery/root/system/bin/ || true
+        [ -f libneeds ] && mv -n libneeds ${GITHUB_WORKSPACE}/workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery/root/ || true
+        [ -f ldcheck ] && mv -n ldcheck ${GITHUB_WORKSPACE}/workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery/root/ || true
+      continue-on-error: true
+
+    - name: Run LDCheck
+      run: |
+        cd workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery/root
+        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ github.event.inputs.FILE_TO_CHECK }}
+        echo "Done checking missing dependencies."
+      continue-on-error: true
         default: 'boot'
         type: choice
         options:
